export const properties = [
  {
    id: 1,
    price: 175000,
    capRate: 9.5,
    address: "2236 S. Van Dyke Rd, Marlette, OH 48453",
    year: 2025,
    type: "Single Family",
    beds: 3,
    baths: 2,
    sqft: 930,
    features: ["Forced Air", "Driveway"],
    images: ["/modern-luxury-florida-house-with-palm-trees-and-su.jpg"],
    verified: true,
    imageCount: 34,
  },
  {
    id: 2,
    price: 199000,
    capRate: 9.93,
    address: "3337 Sylvanhurst Drive, Cleveland Heights, OH",
    year: 1925,
    type: "Multi Family",
    beds: 2,
    baths: 2,
    sqft: 1334,
    features: ["Forced Air", "Detached Garage"],
    images: ["/modern-miami-beachfront-condo.jpg"],
    verified: true,
    imageCount: 21,
  },
  {
    id: 3,
    price: 149000,
    capRate: 8.61,
    address: "591 Hemlock Drive, Euclid, OH 44132",
    year: 1952,
    type: "Single Family",
    beds: 3,
    baths: 2,
    sqft: 1200,
    features: ["Forced Air", "Attached Garage"],
    images: ["/orlando-family-house-with-pool.jpg"],
    verified: true,
    imageCount: 15,
  },
  {
    id: 4,
    price: 1499000,
    capRate: 8.91,
    address: "2236 S. Van Dyke Rd, Michigan, OH 48453",
    year: 1973,
    type: "Luxury Villa",
    beds: 5,
    baths: 4,
    sqft: 3500,
    features: ["Forced Air", "Driveway", "Pool"],
    images: ["/tampa-luxury-villa-with-garden.jpg"],
    verified: true,
    imageCount: 42,
  },
  {
    id: 5,
    price: 325000,
    capRate: 7.25,
    address: "1847 Oceanview Blvd, Fort Lauderdale, FL 33301",
    year: 2018,
    type: "Waterfront",
    beds: 4,
    baths: 3,
    sqft: 2100,
    features: ["Central AC", "Waterfront", "Dock"],
    images: ["/fort-lauderdale-waterfront-house.jpg"],
    verified: true,
    imageCount: 28,
  },
  {
    id: 6,
    price: 275000,
    capRate: 8.15,
    address: "892 Modern Lane, Jacksonville, FL 32207",
    year: 2020,
    type: "Townhouse",
    beds: 3,
    baths: 2.5,
    sqft: 1650,
    features: ["Modern Design", "Garage", "Patio"],
    images: ["/jacksonville-modern-townhouse.jpg"],
    verified: true,
    imageCount: 19,
  },
];
